https://towardsdatascience.com/the-complete-guide-to-linear-regression-in-python-3d3f8f06bf8

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
array = np.arange(100) +1

In [11]:
array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [12]:
data = np.array(array)

In [15]:
p_value = 5

In [16]:
y = data[p_value:]

array([  6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
        32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
        97,  98,  99, 100])

In [18]:
rows = len(y)

In [19]:
x = np.ones((rows, p_value+1))

In [27]:
data[0:p_value+0][::-1]

array([5, 4, 3, 2, 1])

In [28]:
for i in range(rows):
    x[i, 1:] = data[i:p_value+i][::-1]

array([ 0.27272727,  0.74545455,  0.47272727,  0.2       , -0.07272727,
       -0.34545455])

In [31]:
x_plus = np.linalg.pinv(x)

In [32]:
a = x_plus.dot(y)

In [37]:
data

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [62]:
class LinearRegression:
    def __init__(self, p_value):
        self.p_value = p_value

    def fit(self, X):
        y = X[self.p_value:]
        x_plus = self.transform_data(X)
        x_plus = np.linalg.pinv(x_plus)
        self.betas = np.dot(x_plus, y)
        
    def transform_data(self, X):
        x = np.ones((len(X)-self.p_value, p_value+1))
        for i in range(rows):
            x[i, 1:] = X[i:p_value+i][::-1]
        return x
        
    def predict(self, X):
        self.fit(X)
        data = self.transform_data(X)
        y_pred = data.dot(self.betas)
        return y_pred


In [63]:
model = LinearRegression(5)

In [64]:
model.fit(data)

In [65]:
model.predict(data)

array([  6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,
        17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,
        28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,
        39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,
        50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
        61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,
        72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,
        83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,
        94.,  95.,  96.,  97.,  98.,  99., 100.])

In [46]:
model.betas

array([ 0.97683306,  1.04580736, -0.04786558])

In [47]:
model.predict(data)

array([ -0.64108273,  11.93078823, -10.31287244])