https://towardsdatascience.com/the-complete-guide-to-linear-regression-in-python-3d3f8f06bf8

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
array = np.arange(100) +1

In [3]:
array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
data = np.array(array)

In [5]:
p_value = 5

In [6]:
y = data[p_value:]

In [7]:
rows = len(y)

In [8]:
x = np.ones((rows, p_value+1))

In [9]:
data[0:p_value+0][::-1]

array([5, 4, 3, 2, 1])

In [10]:
for i in range(rows):
    x[i, 1:] = data[i:p_value+i][::-1]

In [11]:
x_plus = np.linalg.pinv(x)

In [12]:
a = x_plus.dot(y)

In [16]:
a

array([ 0.27272727,  0.74545455,  0.47272727,  0.2       , -0.07272727,
       -0.34545455])

In [13]:
from sklearn.datasets import make_regression
from matplotlib import pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

In [14]:
X, y, coefficients = make_regression(
    n_samples=50,
    n_features=1,
    n_informative=1,
    n_targets=1,
    noise=5,
    coef=True,
    random_state=1
)

In [20]:
U, sigma, VT = np.linalg.svd(data, full_matrices=False)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

array([[-0.03635982],
       [ 0.02783672],
       [-0.09969196],
       [-0.02514115],
       [ 0.30623084],
       [-0.02797087],
       [-0.08919806],
       [ 0.24677087],
       [ 0.07326694],
       [ 0.25440489],
       [-0.33557929],
       [ 0.03417933],
       [ 0.10819486],
       [-0.01791819],
       [-0.12323647],
       [-0.12942207],
       [-0.12799746],
       [ 0.12618205],
       [-0.07701087],
       [-0.0928781 ],
       [ 0.0074081 ],
       [ 0.16690815],
       [-0.15644579],
       [-0.11098891],
       [ 0.13145778],
       [-0.3003819 ],
       [ 0.07732927],
       [-0.09787205],
       [ 0.16531095],
       [-0.13644126],
       [-0.16291111],
       [-0.04701052],
       [ 0.24200994],
       [ 0.13135065],
       [ 0.08497824],
       [ 0.23684011],
       [-0.16037129],
       [-0.05599762],
       [-0.16047743],
       [-0.10894053],
       [ 0.08999222],
       [-0.00184658],
       [ 0.04651797],
       [ 0.21318483],
       [-0.10084863],
       [ 0